### ISSUE TITLE
HACS

### ISSUE THREAD

**Issue by tuimz** [sendorm/timedcover#1]
Can we get this into HACS? https://github.com/custom-components/hacs
I'd be happy to help write the required files ;)

**Comment by hidra000** [comment]
I think its a good idea, love hacs for this kind of things. But the code needs some extra love and care. Should be nice to have feedback back about the procentage when you pauze the screen.

**Comment by tuimz** [comment]
I have added this repository as a custom repository. Works for me for now. If you ever need help writing files to get it into hacs let me know.
